import { DataGraph } from '../graph/models';
import * as fs from 'fs';

export function generateMarkdownReport(graph: DataGraph, outputPath: string) {
  let md = `# Data Contracts and Metadata Report\n\n`;
  md += `Generated by data-archify.\n\n`;

  for (const node of graph.nodes) {
    if (!node.metadata && !node.columns) {
      continue;
    }

    md += `## ${node.name}\n`;
    md += `- **ID:** \`${node.id}\`\n`;
    md += `- **Type:** \`${node.type}\`\n`;
    md += `- **Group:** \`${node.group}\`\n`;

    if (node.metadata) {
      md += `### Metadata\n`;
      if (node.metadata.criticality) md += `- **Criticality:** ${node.metadata.criticality}\n`;
      if (node.metadata.owner) md += `- **Owner:** ${node.metadata.owner}\n`;
      if (node.metadata.sla) md += `- **SLA:** ${node.metadata.sla}\n`;
      if (node.metadata.slo) md += `- **SLO:** ${node.metadata.slo}\n`;
    }

    if (node.columns && node.columns.length > 0) {
      md += `### Columns\n`;
      md += `| Name | Type | Description |\n`;
      md += `|------|------|-------------|\n`;
      for (const col of node.columns) {
        const typeStr = col.type ? `\`${col.type}\`` : 'N/A';
        const descStr = col.description ? col.description.replace(/\n/g, ' ') : '';
        md += `| **${col.name}** | ${typeStr} | ${descStr} |\n`;
      }
    }
    
    // Find upstreams
    const upstreams = graph.edges.filter(e => e.target === node.id).map(e => e.source);
    if (upstreams.length > 0) {
      md += `### Upstream Dependencies\n`;
      for (const up of upstreams) {
        md += `- \`${up}\`\n`;
      }
    }

    md += `\n---\n\n`;
  }

  fs.writeFileSync(outputPath, md, 'utf8');
}
